// Code generated by Axiom CLI; DO NOT EDIT.
package axiom;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * AxiomContext — the single injection point for platform capabilities (ADR-001).
 *
 * <p>A node receives one {@code AxiomContext} per invocation and reaches every
 * platform capability through it:
 * <pre>
 *   String key = ax.secrets().get("OPENAI_KEY").orElse("");
 *   var turns  = ax.agent().memory().session("s1").history().last(20);
 *   var nodes  = ax.reflection().flow().nodes();
 * </pre>
 *
 * <p>Node code never talks to the platform directly — capabilities are
 * consolidated here to prevent signature drift across SDK versions (ADR-001).
 * All capability types are nested so the whole contract lives in one file.
 */
public interface AxiomContext {

    Logger log();

    Secrets secrets();

    Agent agent();

    String executionId();

    String flowId();

    String tenantId();

    Reflection reflection();

    Mutation mutation();

    // ── Logging & secrets ───────────────────────────────────────────────────

    /** Structured logger pre-configured for a single node invocation. */
    interface Logger {
        void debug(String msg, Map<String, String> attrs);
        void info(String msg, Map<String, String> attrs);
        void warn(String msg, Map<String, String> attrs);
        void error(String msg, Map<String, String> attrs);

        default void debug(String msg) { debug(msg, Map.of()); }
        default void info(String msg)  { info(msg, Map.of()); }
        default void warn(String msg)  { warn(msg, Map.of()); }
        default void error(String msg) { error(msg, Map.of()); }
    }

    /** Read-only access to tenant secrets resolved by the platform. */
    interface Secrets {
        Optional<String> get(String name);
    }

    // ── Agent memory hierarchy (ADR-002) ────────────────────────────────────
    // ax.agent().memory().session(id).history().last(20)

    /** A single turn in a conversation session. */
    record ConversationTurn(String role, String content, String sessionId, long timestamp) {}

    /** A single memory entry retrieved from the memory layer. */
    record MemoryEntry(String id, String content, double relevance, String scopeLevel, String memoryType) {}

    /** Conversation history for a single session. */
    interface SessionHistory {
        List<ConversationTurn> last(int n);
        void append(String role, String content);
    }

    /** Memory and conversation history scoped to a single session. */
    interface SessionMemory {
        List<MemoryEntry> search(String query, int limit);
        String write(String content, double importance);
        SessionHistory history();
        /** Formally close the session and trigger consolidation. */
        void end();
    }

    /** Durable memory for the agent, scoped to flow and tenant. */
    interface AgentMemory {
        SessionMemory session(String sessionId);
        List<MemoryEntry> search(String query, int limit);
        String write(String content, double importance);
    }

    /** The agent: the entry point to durable memory. */
    interface Agent {
        AgentMemory memory();
    }

    // ── Flow reflection (ADR-050 / ADR-055) ─────────────────────────────────

    /** A node in the running flow graph. */
    record ReflectionNode(
        int instanceId, String nodeUlid, String name, String packageName,
        String packageVersion, String nodeType, String inputMessageName,
        String outputMessageName, String canvasNodeId) {}

    /** ADR-055 / GAP-4: agent-readable digest of an edge's dispatch condition. */
    record ConditionSummary(String field, String op, List<String> operands) {}

    /** An edge in the running flow graph. {@code conditionSummary} is null when the edge is unconditional. */
    record ReflectionEdge(
        int srcInstance, int dstInstance, String canvasEdgeId, boolean hasCondition,
        boolean hasAdapter, int maxIterations, ConditionSummary conditionSummary) {}

    /** The executing position within the (possibly nested) flow. */
    record FlowPosition(
        int currentInstance, int depth, Map<Integer, Integer> loopIterations,
        List<String> subflowStackGraphIds) {}

    /** Read-only view of the running flow graph. */
    interface FlowReflection {
        List<ReflectionNode> nodes();
        List<ReflectionEdge> edges();
        List<ReflectionEdge> loopEdges();
        FlowPosition position();
        String graphId();
    }

    interface Reflection {
        FlowReflection flow();
    }

    // ── Flow mutation (ADR-051 / ADR-054) ───────────────────────────────────

    /** Canvas placement for a mutation-added node. */
    record CanvasPosition(double x, double y) {}

    /** ADR-054: a conditional dispatch for a mutation-added edge. */
    record EdgeCondition(String op, String field, String value) {}

    /** Buffered, additive mutation of the running flow graph. */
    interface FlowMutation {
        int addNode(String packageName, String packageVersion, CanvasPosition canvasPosition);
        void addEdge(int srcInstance, int dstInstance, EdgeCondition condition);
    }

    interface Mutation {
        FlowMutation flow();
    }
}
